In [2]:
import numpy as np
import matplotlib.pyplot as plt
from optical_element_io import *
from column_io import OpticalColumn
# from automation import optimize_column_for_mag
from automation import calculate_c3
# from automation_library import calculate_c3
from importlib import reload
import asyncio

In [2]:
obj = StrongMagLens('/home/trh/data/std_obj/trees/cb/obj41.dat')
obj.write('/home/trh/data/columns/mag_tests/obj41_magadj.dat')

Reading file /home/trh/data/std_obj/trees/cb/obj41.dat 
with title: MAGNETIC SATURATED CIRCUIT (SYMMETRIC LENS)
Warning! This data file seems to have curvature coordinates. Setting so=True.


In [3]:
tl1 = StrongMagLens('/home/trh/data/transfer/trees/c/transfer02.dat')
tl1.write('/home/trh/data/columns/mag_tests/transfer02_magadj.dat')

Reading file /home/trh/data/transfer/trees/c/transfer02.dat 
with title: MAGNETIC SATURATED CIRCUIT (ASYMMETRIC LENS)
Warning! This data file seems to have curvature coordinates. Setting so=True.


In [4]:
tl2 = StrongMagLens('/home/trh/data/transfer/trees/c/transfer02.dat')
tl2.write('/home/trh/data/columns/mag_tests/transfer02_magadj2.dat')

Reading file /home/trh/data/transfer/trees/c/transfer02.dat 
with title: MAGNETIC SATURATED CIRCUIT (ASYMMETRIC LENS)
Warning! This data file seems to have curvature coordinates. Setting so=True.


In [5]:
col = OpticalColumn(obj=obj,tl_list=[tl1,tl2])

In [6]:
col.imgcondfilename = '/home/trh/data/columns/mag_tests/mag_col00.dat'

In [7]:
obj.pos_adj = False
obj.f_adj = True
tl1.pos_adj = True
tl1.f_adj = True
tl2.pos_adj = True
tl2.f_adj = True
obj.lens_pos = 0
obj.lens_excitation = 60000
obj.excitation_flag = 'f'
tl1.lens_pos = 10
tl1.lens_excitation = 14000
tl1.excitation_flag = 'v1'
tl2.lens_pos = 20
tl2.lens_excitation = 14000
tl2.excitation_flag = 'v2'

In [9]:
optimize_column_for_mag(col)

Initial_magnification: -2.4313
Hit bounds
[[-3482.89184686  3482.89184686]
 [    0.          2000.        ]
 [-2777.96659927  2777.96659927]
 [    0.          2000.        ]
 [-2777.96659927  2777.96659927]
 [    0.          2000.        ]] [6.0e+04 1.0e+01 1.4e+04 2.0e+01 1.4e+04 5.0e+01]
Hit bounds
[[-3482.89184686  3482.89184686]
 [    0.          2000.        ]
 [-2777.96659927  2777.96659927]
 [    0.          2000.        ]
 [-2777.96659927  2777.96659927]
 [    0.          2000.        ]] [6.3e+04 1.0e+01 1.4e+04 2.0e+01 1.4e+04 5.0e+01]
Hit bounds
[[-3482.89184686  3482.89184686]
 [    0.          2000.        ]
 [-2777.96659927  2777.96659927]
 [    0.          2000.        ]
 [-2777.96659927  2777.96659927]
 [    0.          2000.        ]] [6.00e+04 1.05e+01 1.40e+04 2.00e+01 1.40e+04 5.00e+01]
Hit bounds
[[-3482.89184686  3482.89184686]
 [    0.          2000.        ]
 [-2777.96659927  2777.96659927]
 [    0.          2000.        ]
 [-2777.96659927  2777.96659927]
 [    0

In [13]:
obj2 = StrongMagLens('/home/trh/data/std_obj/trees/cb/obj40.dat')
obj2.write('/home/trh/data/columns/mag_tests/obj40_test.dat')

Reading file /home/trh/data/std_obj/trees/cb/obj40.dat 
with title: MAGNETIC SATURATED CIRCUIT (SYMMETRIC LENS)
Warning! This data file seems to have curvature coordinates. Setting so=True.


In [14]:
col2 = OpticalColumn(oe=obj2)

In [15]:
obj2.calc_field()

In [16]:
col2.write_opt_img_cond_file('/home/trh/data/columns/mag_tests/test_col00.dat')

In [17]:
calculate_c3(obj2,col2,curr_bound=3)

f: -15.4596, C3: 3.26572


100

In [3]:
obj3 = StrongMagLens('/home/trh/data/transfer/trees/c/transfer02.dat')
obj3.write('/home/trh/data/columns/mag_tests/transfer02_c3_test.dat')

Reading file /home/trh/data/transfer/trees/c/transfer02.dat 
with title: MAGNETIC SATURATED CIRCUIT (ASYMMETRIC LENS)
Warning! This data file seems to have curvature coordinates. Setting so=True.


In [4]:
col3 = OpticalColumn(oe=obj3)

In [5]:
obj3.calc_field()

In [6]:
col3.write_opt_img_cond_file('/home/trh/data/columns/mag_tests/test_col00.dat')

In [7]:
calculate_c3(obj3,col3,curr_bound=3)

f: 10.1172, C3: 6.05641


100